"""
model_optimize.py — INT8 quantization / optimization utility (Track 1).

The submitted INT8 model is produced by quantization-aware training (QAT) inside
model_training.py, which selects the QAT checkpoint with the best *exact* INT8
validation accuracy (352/364). This script provides a standalone way to
regenerate the deployable INT8 artifacts from a saved Keras model and to verify
them, using the same TFLite full-integer converter as the training pipeline.

It performs:
  1. Load a trained Keras model (float or QAT).
  2. Full-integer INT8 conversion with a representative dataset (int8 in/out).
  3. Export the .tflite and the C header consumed by the Zephyr/QEMU app.
  4. Report the model size, TFLite operators, and INT8 validation accuracy.

Run (defaults reproduce a re-export from the winning float model):
    set TF_USE_LEGACY_KERAS=1
    python src\\model_optimize.py

Options:
    python src\\model_optimize.py --model <path.keras> --from-qat \\
        --tflite <out.tflite> --header <out.h>

Note: post-training quantization of the plain float model is an approximation of
the shipped artifact. The exact submitted model comes from the QAT pipeline in
model_training.py; the canonical artifacts already exist at
model/quantized_model/model_quant.tflite and src/qemu_app/src/model_data.h.
"""
import argparse
import os

os.environ.setdefault("TF_USE_LEGACY_KERAS", "1")

import numpy as np

import model_training as training


DEFAULT_MODEL = os.path.join(training.MODEL_DIR, "float_model_v16.keras")
DEFAULT_TFLITE = os.path.join(
    training.MODEL_DIR, "quantized_model", "model_quant_v16_reexport.tflite")
DEFAULT_HEADER = os.path.join(
    training.SCRIPT_DIR, "qemu_app", "src", "model_data_v16_reexport.h")


def tflite_operator_names(tflite_path):
    """Return the unique (non-delegate) TFLite operator names."""
    interpreter = v5.tf.lite.Interpreter(model_path=tflite_path)
    return sorted({
        op["op_name"]
        for op in interpreter._get_ops_details()  # pylint: disable=protected-access
        if op["op_name"] != "DELEGATE"
    })


def write_c_header(tflite_data, header_path):
    """Emit the model as a 16-byte-aligned C array for the Zephyr app."""
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    hex_values = ", ".join(f"0x{byte:02x}" for byte in tflite_data)
    with open(header_path, "w", encoding="utf-8") as file:
        file.write("/* Auto-generated by model_optimize.py — do not edit. */\n")
        file.write("#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n")
        file.write("#include <stddef.h>\n\n")
        file.write(f"/* Model size: {len(tflite_data):,} bytes */\n")
        file.write(
            "alignas(16) const unsigned char model_data[] = "
            f"{{\n  {hex_values}\n}};\n\n"
        )
        file.write(
            f"const unsigned int model_data_len = {len(tflite_data)};\n\n"
        )
        file.write("#endif /* MODEL_DATA_H */\n")


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=DEFAULT_MODEL,
                        help="Path to the trained Keras model.")
    parser.add_argument("--from-qat", action="store_true",
                        help="Set if the model was produced by QAT.")
    parser.add_argument("--tflite", default=DEFAULT_TFLITE,
                        help="Output INT8 .tflite path.")
    parser.add_argument("--header", default=DEFAULT_HEADER,
                        help="Output C header path.")
    return parser.parse_args()


def main():
    args = parse_args()

    print("=" * 72)
    print("  INT8 QUANTIZATION / OPTIMIZATION")
    print("=" * 72)
    print(f"  Source model : {args.model}")

    print("\n[1/4] Loading representative and validation data …")
    x_train, _ = training.load_dataset(training.TRAIN_DIR, oversample=True)
    x_val, y_val = training.load_dataset(training.VAL_DIR, oversample=False)

    print("\n[2/4] Loading Keras model …")
    model = training.keras.models.load_model(args.model, compile=False)
    print(f"  Parameters : {model.count_params():,}")

    print("\n[3/4] Full-integer INT8 conversion …")
    tflite_data = training.convert_to_int8(
        model, x_train, args.tflite, from_qat=args.from_qat)
    operators = tflite_operator_names(args.tflite)
    write_c_header(tflite_data, args.header)
    print(f"  TFLite      : {args.tflite}")
    print(f"  C header    : {args.header}")
    print(f"  Model size  : {len(tflite_data):,} bytes "
          f"({len(tflite_data) / 1024.0:.1f} KB)")
    print(f"  Operators   : {', '.join(operators)}")

    print("\n[4/4] INT8 validation …")
    int8_acc, per_class = training.evaluate_int8(
        args.tflite, x_val, y_val)
    correct = int(np.sum(per_class[:, 0]))
    total = int(np.sum(per_class[:, 1]))
    print(f"  INT8 accuracy : {int8_acc:.2f}% ({correct}/{total})")
    print("=" * 72)


if __name__ == "__main__":
    main()
